# name: Publish new version

on:
  pull_request:
    branches: 
    - main  
  push:
    branches: 
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 24
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Prepare
        run: |
          npm i -g npm@7
          npm ci
      - name: Test
        run: |
          npm test
          npm run lint
      - name: Build
        run: |
          npm run build


